
[tool.poetry]
name = "sinklit-bot"
version = "0.1.0"
description = ""
authors = ["yourname <youremail@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
python-telegram-bot = "20.3"
flask = "^3.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
